version: '3.8'
services:
  dev-db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    ports:
      - 5434:5432
    networks:
      - freecodecamp
  test-db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    ports:
      - 5435:5432
    networks:
      - freecodecamp
networks:
  freecodecamp:
